#!/bin/sh

NC='\033[0m'
GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[0;36m'

# Get current branch name
current_branch=$(git symbolic-ref --short HEAD)
echo -e "${GREEN}[INFO]${NC} 현재 branch name: ${BLUE}${current_branch}${NC}"

# Check if the current branch name follows project's naming convention
if [[ ! $current_branch =~ ^(frontend|backend|infra|ai)\/RING-[1-9][0-9]*$ ]]; then
	echo -e "${RED}[ERROR]${NC} 현재 branch name의 형식이 맞지 않습니다. (ex. frontend/RING-1, backend/RING-2, infra/RING-3, ai/RING-4)"
	exit 1
fi

# Apply linter and formatter (only on frontend)
cd frontend
npx lint-staged